[package]
name = "pacbomber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", features = ["jpeg"] }
bevy_mod_outline = "0.2.2"
bevy_tweening = "0.5.0"
